enum Model {
  USER = 'USER',
  WEDDING = 'WEDDING',
  SHARED_MESSAGE = 'SHARED_MESSAGE',
  SHARED_PHOTO = 'SHARED_PHOTO',
  ALBUM_PHOTO = 'ALBUM_PHOTO',
  GUEST = 'GUEST',
  GIFT = 'GIFT'
}

export default Model
